### ISSUE TITLE
Milestone 3 tasks

### ISSUE THREAD

**Issue by christopheralex** [UBC-MDS/spotify-explorer-py#44]
- [ ] Adds dockerfile and installation instructions in Readme.md. (Dockerfile and docker-compose.yml)
> xxxx 
- [ ] Add favicon.ico in assert folder and app title.
> xxxx
- [ ] Peer review of group 3 https://github.com/UBC-MDS/netviz
> xxxxx
- [ ] Create issue for Peer review
> xxxxx
- [ ] Create R repository (Ask Florencia on if complete implementation)
> xxxx
- [ ]  Comparing technologies https://github.com/UBC-MDS/dash-tableau-shiny_comparison/blob/main/group_2.md
> Resources - Famous conferences - workshops - twitter accounts to follow - blogpost/webpages - sources of material about this technology - Podcasts - Discord/Slack communities - YouTube Channels. Provide the most extensive list of resources you can with a short description for each. Where do you find the most material? Where would you suggest a beginner start learning about this technology?

**Comment by christopheralex** [comment]
Someone has to review the R repo as well :) 

https://github.com/UBC-MDS/spotify-explorer-R/issues/3#issue-1163042685
