### ISSUE TITLE
Milestone 4 tasks Finalizing your dashboards

### ISSUE THREAD

**Issue by xiangwxt** [UBC-MDS/spotify-explorer-py#52]
1. Improving your app
> Include at least five improvements to your app
- [ ] (i) new things explained in the lecture that you would like to add
- [ ] (ii) comments from the peer review you received
- [ ] (iii) TA feedback from previous milestones
- [ ] You should paste the link to the commits in the submission with a brief description of the change
> Include collapse button with app description https://github.com/UBC-MDS/dashboard/commit/2314bb8f6ccc856d61ebf547e13e0da3a56b690a

**Comment by jennifer-hoang** [comment]
Peer review: https://github.com/UBC-MDS/DSCI532-peer-review/issues/15

**Comment by jennifer-hoang** [comment]
Improvement Ideas:
- Add interactivity between artist and time/distribution plots (Jenn)

**Comment by christopheralex** [comment]
1. Add selection interval to the plots. 
2. Link the bar plot of top artists and the other 2 graphs. 
3. Change background of plots or add border to plots. 
4. Add loading symbol for the switch between apps.
5. From feedback received - Reduce plot sizes .

**Comment by jennifer-hoang** [comment]
Jenn's To Do:
- [ ]  Interactivity (2)
- [ ]  Resize top artists plot (5)

**Comment by xiangwxt** [comment]
8. For the “Song characteristics distribution between two popularity classes”, it would be helpful to clearly specify the threshold set for “Popular” versus “Not-Popular”, both on the chart itself and the README. - Thea
9. The documentation is easy to understand, kudos to the team. One recommendation is to include a table of contents to the README.md.

**Comment by michelle-wms** [comment]
Hi Chris, can u take a look at this peer review feedback too: 
The data needs to be more carefully filtered as there are duplicate tracks. For example, based on the Artist's popularity record chart, there are 123 records but the number of unique observations for “The Chainsmokers” is ~60.
